global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules"
  - "record.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: nodeexporter
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: grafana
    scrape_interval: 5s
    static_configs:
      - labels:
          container: grafana
    dns_sd_configs:
      - names:
          - grafana
        type: A
        port: 3000  
  - job_name: thanos
    scrape_interval: 5s
    file_sd_configs:
    - files:
      - 'targets.json'
  # - job_name: 'services'
  #   scrape_interval: 5s
  #   relabel_configs:
  #     - action: replace
  #       source_labesl: [job]
  #       target_label: address
  #   dns_sd_configs:
  #     - names:
  #         - grafana
  #         - cadvisor
  #         - prometheus
  #         - nodeexporter
  #         - alertmanager
  #       type: A
  #       port: 9100


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

remote_write:
  - url: "http://thanos-01:19291/api/v1/receive"
    queue_config:
      max_samples_per_send: 500
      batch_send_deadline: 5s
      min_backoff: 50ms
      max_backoff: 500ms