{
 "title": "Four Golden Signals",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{}[$__interval]) / rate(http_request_duration_seconds_count{}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "http_requests_total{} / http_requests_total{code=~\"5..\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}